name: Windows RDP via Ngrok
on: [push, workflow_dispatch]

jobs:
  rdp-access:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .\ngrok\

      - name: Authenticate Ngrok
        run: .\ngrok\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Service -Name "TermService" -Force

      - name: Set Secure Password (via GitHub Secrets)
        run: |
          $password = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $password -ErrorAction Stop

      - name: Start Ngrok Tunnel (RDP on 3389)
        run: Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow

      - name: Get Ngrok Public URL
        run: |
          Start-Sleep -Seconds 5  # Wait for Ngrok to initialize
          (Invoke-WebRequest -Uri http://localhost:4040/api/tunnels -UseBasicParsing).Content | Out-File ngrok_url.txt
          Get-Content ngrok_url.txt
