name: Windows RDP via Ngrok
on: [workflow_dispatch]

jobs:
  rdp-access:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .\ngrok\

      - name: Authenticate Ngrok
        run: .\ngrok\ngrok.exe authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Service -Name "TermService" -Force

      - name: Create or Update RDP User
        run: |
          $Password = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
          if (-not (Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "runneradmin" -Password $Password -AccountNeverExpires
          } else {
            Set-LocalUser -Name "runneradmin" -Password $Password
          }
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "runneradmin"

      - name: Start Ngrok Tunnel (RDP on 3389)
        run: Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow

      - name: Wait for Ngrok to initialize (15 seconds)
        run: Start-Sleep -Seconds 15

      - name: Get Ngrok Public URL (with retry logic)
        run: |
          $retryCount = 0
          $maxRetries = 5
          $success = $false

          while ($retryCount -lt $maxRetries -and -not $success) {
              try {
                  $response = Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels" -UseBasicParsing -ErrorAction Stop
                  $response.Content | Out-File ngrok_url.txt
                  Get-Content ngrok_url.txt
                  $success = $true
              } catch {
                  $retryCount++
                  Write-Host "Attempt $retryCount failed. Retrying in 5 seconds..."
                  Start-Sleep -Seconds 5
              }
          }

          if (-not $success) {
              Write-Host "Failed to get Ngrok URL after $maxRetries attempts."
              exit 1
          }
